export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const ANALITIC_ROUTE = '/analytics'
export const USER_MANAGE_ROUTE = '/user-manage'
export const DISCIPLINE_MANAGE_ROUTE = '/discipline-manage'
export const GROUP_MANAGE_ROUTE = '/group-manage'
export const DOWNLOAD_ROUTE = '/download'
